introduction and features
IT-forward/IT-forward.github.io pull request #11
Opened 2021-05-18 14:44 UTC by Husan-Eshonqulov

Closes #6 

Introduction and features sections are ready for your commits

2021-05-20 11:56 UTC, bahriddin requested changes
2 ta asosiy fikr bor:
1) Eski package'larni va import qatorlarini o'chirish;
2) Bootstrapning html'ga klass bergan joylarining o'rniga React-Bootstrap komponentlarini ishlatish.

Shularni to'g'irlasangiz juda yaxshi bo'lardi 👍

2021-05-20 11:56 UTC, bahriddin commented on package.json
> +    "popper.js": "^1.16.1",
Bularga hojat yo'q, shekilli. O'chirsangiz bo'ladi.

2021-05-20 11:56 UTC, bahriddin commented on src/LandingPage/LandingPage.tsx
> +import { Nav, Navbar, NavDropdown } from "react-bootstrap";
`NavDropdown` ni kodda hech qayerda ishlatmagansiz. 
```suggestion
import { Nav, Navbar } from "react-bootstrap";
```

2021-05-20 11:56 UTC, bahriddin commented on src/LandingPage/LandingPage.tsx
> +import 'bootstrap/dist/css/bootstrap.min.css';
Ortiqcha

2021-05-20 11:56 UTC, bahriddin commented on src/index.tsx
> +import 'bootstrap/dist/css/bootstrap.css';
Ortiqcha

2021-05-20 11:56 UTC, bahriddin commented on src/LandingPage/LandingPage.tsx
> +                </div>
Shu va shu kabi layout'ning `container`, `col` va `row` kabi divlarning o'rniga React-Bootstrap paketi komponentlarini ishlatsangiz yaxshiroq bo'lardi: https://react-bootstrap.github.io/layout/grid/
Umuman, iloji boricha React-Bootstrap paketining komponentlaridan ishlatsangiz yaxshiroq, chamamda.

2021-05-20 16:44 UTC, Husan-Eshonqulov commented on package.json
> +    "popper.js": "^1.16.1",
Ok

2021-05-20 16:47 UTC, Husan-Eshonqulov commented on src/LandingPage/LandingPage.tsx
> +                </div>
👌 O'zimga ham shu narsa yoqmay turgandi. Css kodi ham kattalashib ketayotgan edi.

2021-05-23 06:30 UTC, bahriddin commented
Husan, biz bilan bog'lanishning dizaynini shablondagi mana bu qismdaka qilolasizmi?

![image](https://user-images.githubusercontent.com/3971918/119250540-0eca2b00-bbe4-11eb-902d-f959b546408b.png)

Mana bu qismni footer deb qarab, tepeadagi rasmdaka orqa fonini kulrang qilsangiz chiroyli chiqadi, menimcha:

![image](https://user-images.githubusercontent.com/3971918/119250555-273a4580-bbe4-11eb-9369-72571a8f64ac.png)

2021-05-23 06:34 UTC, bahriddin commented
Keyin mana bu `hover` bo'lganida kattalashib yonidagilarni surishi chiroyli ko'rinmayapti:

https://user-images.githubusercontent.com/3971918/119250608-a3348d80-bbe4-11eb-8510-e1e41164c949.mov

2021-05-23 06:35 UTC, bahriddin requested changes
Dizayn tarafdan o'zgarishlar qilish kerak. Fikrlarimni qoldirdim.

2021-05-23 07:57 UTC, bahriddin commented
Keyin Biz bilan bog'lanishdagi ijtimoiy tarmoq ikonkalariniyam shablondaka qiling:

![image](https://user-images.githubusercontent.com/3971918/119252544-45a63e00-bbf0-11eb-9a6b-214cc883482f.png)

2021-05-23 15:34 UTC, Husan-Eshonqulov commented
Aha commitlarni to'g'irlaymiz 👌

2021-05-26 11:13 UTC, husan-eshonqulov commented
Ustoz endi bir ko'ringchi. Ertalab ko'rsatgan xatolarizni to'g'irladim

2021-05-27 11:46 UTC, bahriddin approved these changes
👏

2021-05-27 12:37 UTC, merged