Husan/member accounts
IT-forward/IT-forward.github.io pull request #23
Opened 2021-06-15 09:49 UTC by Husan-Eshonqulov

Closes #13

2021-06-16 11:49 UTC, bahriddin reviewed
`husan-img.jpg` rasmingiz eni va bo'yi bir xil bo'lishi kerak.

2021-06-16 11:52 UTC, bahriddin reviewed
Proyekt nomlarining orqa foni oq bo'lsin degandim: 
![image](https://user-images.githubusercontent.com/3971918/122214158-1cc25180-ceed-11eb-8296-eb41d1585be9.png)

Mana bunaqa bo'lishini aytgandim:
![image](https://user-images.githubusercontent.com/3971918/122216903-3d3fdb00-cef0-11eb-88be-6a86e5b1a2b2.png)

Keyin proyekt ustiga olib borganda mana bu yerdagi (https://www.w3schools.com/howto/howto_css_image_overlay.asp `Fade in a box:` misol) kabi orqa qorayib 2 ta button paydo bo'lishi kerak: Bittasi `fa-link` ikonkasi bo'lib bossa netlify linki, ikkinchisi github ikonkasi bilan bossa, github repoga.

2021-06-16 12:21 UTC, bahriddin requested changes
1. Rasmlar uchun alohida assets degan papka yaratib hammasini o'shani ichiga qo'yasiz.
2. Har bir komponentni yaratganda shunchaki xususiy misol uchun ishlasa bo'ldi deb emas, istalgan kontent bilan ishlaydigan qilib yarating. Icon1, projects, Testimonial komponentlaringiz bunga misol. O'zingiz o'ylang, ertaga shu komponentni ishlatmoqchi bo'lgan boshqalar qanday ishlatishadi?
3. Konfliktlarni hal qilib qo'ying.

2021-06-16 12:21 UTC, bahriddin commented on src/memberAccounts/MemberAccount.tsx
> +        </Col>
`Icon1` ni alohida komponentga olish o'rniga shu qismni to'liq alohida komponentga olsangiz yaxshimasmidi?

2021-06-24 18:22 UTC, Husan-Eshonqulov commented
Ustoz bir qarab beringchi. Konflikt fayllarni keyin hal qilaman

2021-06-25 03:25 UTC, bahriddin commented
Ishlashi xuddi aytganimdek lekin ikonkalarni kulrang hudud vertikal markaziga joylashtirolasizmi?
![image](https://user-images.githubusercontent.com/3971918/123365003-c58d4280-d5b8-11eb-80bd-439168039028.png)

2021-06-25 03:42 UTC, bahriddin requested changes
Ko'rinishi avvalgidan ancha yaxshi. 1-2 ta takliflarimni qoldiryapman TS va ko'rinishi bo'yicha.

2021-06-25 03:42 UTC, bahriddin commented on src/memberAccounts/MemAccount.tsx
> +          <Header headerInfo={headerInfo} />
Shu joyida hamma proplarni headerInfo'ning ichiga tiqish shartmas. Qaytamga to'g'ridan-to'g'ri bersak kodimiz qisqa va tushunarliroq bo'lardi nazarimda. Qolgan o'zgarishlar uchun `Header.tsx` faylingizdagi kommentimga qarang. 
```suggestion
          <Header {...headerInfo} />
```

2021-06-25 03:42 UTC, bahriddin commented on src/memberAccounts/components/header/Header.tsx
> +  };
```suggestion
    fullName: string;
    profession: string;
    summary: string;
    separated: SeparatedType;
    about: string;
    image: string;
```

2021-06-25 03:42 UTC, bahriddin commented on src/memberAccounts/components/header/Header.tsx
> +  const image = props.headerInfo.image;
```suggestion
function Header({
  fullName,
  profession,
  summary,
  about,
  separated,
  image,
}: HeaderType) {
```

2021-06-25 03:42 UTC, bahriddin commented on src/memberAccounts/MemAccount.tsx
> +          <Facts factsInfo={factsInfo} />
Lekin `factsInfo` kabi ko'plikdagi array bo'lib kelayotgan narsalarni bitta prop ichiga tiqqaningiz yaxshi. Ya'ni shunday qolaversin 👍

2021-06-29 13:25 UTC, husan-eshonqulov commented
Ustoz keyin data qayerda turadi. Index.js dan boshqa yangi faylga olib qo'yaymi

2021-07-22 16:20 UTC, Otabekkadirov approved these changes, later dismissed

2022-11-15 10:37 UTC, bahriddin approved these changes

2022-11-15 10:37 UTC, merged